/**
 * 链接 hover 时的样式
 */
const ANCHOR_HOVER_CLASS_NAME = "has-text-link"

const ADD_DIALOG_ID_NAME = 'adddialog';
const EDIT_DIALOG_ID_NAME = 'editdialog';
const DELETE_DIALOG_ID_NAME = 'deletedialog';

const ADD_OPERATION_ID_NAME = 'addlink';
const EDIT_OPERATION_ID_NAME = 'editlink';
const EDLETE_OPERATION_ID_NAME = 'deletelink';

const OPERATION_TYPE_MAP = {
  ADD: "add",
  EDIT: "edit",
  DELETE: "delete",
}

const OPERATION_ID_NAME_MAP = {
  [OPERATION_TYPE_MAP.ADD]: ADD_OPERATION_ID_NAME,
  [OPERATION_TYPE_MAP.EDIT]: EDIT_OPERATION_ID_NAME,
  [OPERATION_TYPE_MAP.DELETE]: EDLETE_OPERATION_ID_NAME
}

const DIALOG_ID_NAME_MAP = {
  [OPERATION_TYPE_MAP.ADD]: ADD_DIALOG_ID_NAME,
  [OPERATION_TYPE_MAP.EDIT]: EDIT_DIALOG_ID_NAME,
  [OPERATION_TYPE_MAP.DELETE]: DELETE_DIALOG_ID_NAME
}
